### ISSUE TITLE
Exemplo Usar com o VIACEP

### ISSUE THREAD

**Issue by scalarerp** [leonardovilarinho/vue-fast-axios#2]
Nota dez o projeto, gostei muito, se puder passar um exemplo com o VIA CEP ficarei agradecido.

https://viacep.com.br/ws/01001000/json/

O parametro '01001000' é o cep e a URL termina com '/json/'

Obrigado.

**Comment by leonardovilarinho** [comment]
Olá,

bom tem um bom tempo que não mexo nesse projeto por falta de tempo, se eu me lembro algo como:

`this.service.append(`/${cep}/json`).get().execute('cep')` deve resolver, mas para garantir assim que tiver tempo vou dar uma olhada.

**Comment by leonardovilarinho** [comment]
Fechando por falta de interatividade
